-- Run this script in your Supabase SQL Editor to sync your schema with the application.
-- WARNING: This will delete all existing data!

DROP TABLE IF EXISTS push_subscriptions CASCADE;
DROP TABLE IF EXISTS telegram_linking_codes CASCADE;
DROP TABLE IF EXISTS daily_message_counts CASCADE;
DROP TABLE IF EXISTS auto_replies CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS user_stats CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS banners CASCADE;
DROP TABLE IF EXISTS payment_methods CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS sub_sub_categories CASCADE;
DROP TABLE IF EXISTS subcategories CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS offers CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS voucher_uses CASCADE;
DROP TABLE IF EXISTS vouchers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- Users Table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password_hash TEXT NOT NULL,
  balance DECIMAL(10, 2) DEFAULT 0,
  role TEXT DEFAULT 'user',
  personal_number TEXT UNIQUE,
  avatar_url TEXT,
  is_vip BOOLEAN DEFAULT false,
  is_banned BOOLEAN DEFAULT false,
  chat_blocked BOOLEAN DEFAULT false,
  blocked_until TIMESTAMPTZ,
  telegram_chat_id BIGINT UNIQUE,
  referred_by_id BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Vouchers Table
CREATE TABLE vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  max_uses INTEGER DEFAULT 1,
  used_count INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Voucher Uses Table
CREATE TABLE voucher_uses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT REFERENCES vouchers(id),
  user_id BIGINT REFERENCES users(id),
  used_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notifications Table
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'info',
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Offers Table
CREATE TABLE offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Categories Table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  special_id INTEGER,
  order_index INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Subcategories Table
CREATE TABLE subcategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id),
  name TEXT NOT NULL,
  image_url TEXT,
  special_id INTEGER,
  parent_subcategory_id BIGINT,
  order_index INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Sub Sub Categories Table
CREATE TABLE sub_sub_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcategory_id BIGINT REFERENCES subcategories(id),
  name TEXT NOT NULL,
  image_url TEXT,
  special_id INTEGER,
  order_index INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcategory_id BIGINT REFERENCES subcategories(id),
  sub_sub_category_id BIGINT REFERENCES sub_sub_categories(id),
  name TEXT NOT NULL,
  sku TEXT,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  image_url TEXT,
  requires_input BOOLEAN DEFAULT false,
  store_type TEXT DEFAULT 'normal',
  min_quantity INTEGER DEFAULT 1,
  price_per_unit DECIMAL(10, 4),
  external_id TEXT,
  available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Payment Methods Table
CREATE TABLE payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  wallet_address TEXT,
  instructions TEXT,
  min_amount DECIMAL(10, 2) DEFAULT 0,
  active BOOLEAN DEFAULT true
);

-- Banners Table
CREATE TABLE banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  order_index INTEGER DEFAULT 0
);

-- Transactions Table
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  payment_method_id BIGINT REFERENCES payment_methods(id),
  amount DECIMAL(10, 2) NOT NULL,
  receipt_image_url TEXT,
  note TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  total_amount DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'new',
  meta TEXT,
  admin_response TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id),
  product_id BIGINT REFERENCES products(id),
  price_at_purchase DECIMAL(10, 2) NOT NULL,
  quantity INTEGER DEFAULT 1,
  extra_data TEXT
);

-- Settings Table
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- User Stats Table
CREATE TABLE user_stats (
  user_id BIGINT PRIMARY KEY REFERENCES users(id),
  total_orders_count INTEGER DEFAULT 0,
  referral_count INTEGER DEFAULT 0,
  login_days_count INTEGER DEFAULT 0,
  last_login_date DATE,
  vouchers_redeemed_count INTEGER DEFAULT 0,
  total_recharge_sum DECIMAL(10, 2) DEFAULT 0,
  active_discount DECIMAL(10, 2) DEFAULT 0,
  has_flaming_theme BOOLEAN DEFAULT false,
  claimed_reward_index INTEGER DEFAULT -1,
  discount_expires_at TIMESTAMPTZ,
  one_product_discount_percent DECIMAL(10, 2) DEFAULT 0,
  profile_badge TEXT,
  custom_theme_color TEXT,
  has_special_support BOOLEAN DEFAULT false,
  has_priority_orders BOOLEAN DEFAULT false
);

-- Messages Table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  guest_id TEXT,
  sender_role TEXT NOT NULL,
  content TEXT,
  image_url TEXT,
  type TEXT DEFAULT 'text', -- 'text', 'image', 'rating_request', 'rating_response'
  rating INTEGER,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto Replies Table
CREATE TABLE auto_replies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_text TEXT NOT NULL,
  reply_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily Message Counts Table
CREATE TABLE daily_message_counts (
  user_id BIGINT REFERENCES users(id),
  guest_id TEXT,
  date DATE DEFAULT CURRENT_DATE,
  count INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, guest_id, date)
);

-- Telegram Linking Codes Table
CREATE TABLE telegram_linking_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  code TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

-- Push Subscriptions Table
CREATE TABLE push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  subscription TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RPC Functions
CREATE OR REPLACE FUNCTION increment_referral_count(user_id_param BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE user_stats SET referral_count = referral_count + 1 WHERE user_id = user_id_param;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION increment_balance(user_id_param BIGINT, amount_param DECIMAL)
RETURNS VOID AS $$
BEGIN
  UPDATE users SET balance = balance + amount_param WHERE id = user_id_param;
END;
$$ LANGUAGE plpgsql;

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE users;
ALTER PUBLICATION supabase_realtime ADD TABLE categories;
ALTER PUBLICATION supabase_realtime ADD TABLE subcategories;
ALTER PUBLICATION supabase_realtime ADD TABLE sub_sub_categories;
ALTER PUBLICATION supabase_realtime ADD TABLE products;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE payment_methods;
ALTER PUBLICATION supabase_realtime ADD TABLE banners;
ALTER PUBLICATION supabase_realtime ADD TABLE offers;
ALTER PUBLICATION supabase_realtime ADD TABLE vouchers;
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
ALTER PUBLICATION supabase_realtime ADD TABLE settings;
ALTER PUBLICATION supabase_realtime ADD TABLE user_stats;
ALTER PUBLICATION supabase_realtime ADD TABLE telegram_linking_codes;
ALTER PUBLICATION supabase_realtime ADD TABLE push_subscriptions;

-- Add is_faq column to auto_replies (run once in Supabase SQL editor)
ALTER TABLE auto_replies ADD COLUMN IF NOT EXISTS is_faq BOOLEAN DEFAULT FALSE;
